export const en = {
  point: 'Point',
  myPurchase: 'My purchase',
  news: 'News',
  notification: 'Notification',
  myPoint: 'My point',
  myPromotion: 'My Promotion',
  myProfile: 'My Profile',
  changPassword: 'Change password',
  setting: 'Setting',
  logout: 'Log out',
  recent: 'Recent',
  viewAll: 'View all',
  system: 'System',
  termAndPolicy: 'Term and policy',
  faq: 'FAQ',
  all: 'All',
  new: 'News',
  toShip: 'To ship',
  toReceive: 'To receive',
  deliveryTo: 'Delivery to',
  productSelected: 'Products which you selected',
  paymentMethod: 'Payment method',
  summary: 'Summary',
  subTotal: 'Sub total',
  promotionAmount: 'Promotion amount',
  shipFee: 'Shipping fee',
  total: 'Total payment',
  cancelInvoice: 'Cancel invoice',
  cartEmpty: 'Your cart is empty',
  shoppingNow: 'Shopping now',
  myCart: 'My cart',
  category: 'Category',
  home: 'Home',
  following: 'Following',
  Fashion: 'Fashion',
  Beauty: 'Beauty',
  Food: 'Food',
  ['Healthy Foods']: 'Healthy Foods',
  myFollow: 'My follow',
  follow: 'Follow',
  products: 'Products',
  addToCart: 'Add to cart',
  productInfo: `Product's info`,
  review: 'Review',
  introduce: 'Introduce',
  madeIn: 'Made in',
  goToCart: 'Go to cart',
  confirmOrder: 'Confirm order',
  payment: 'Payment',
  change: 'Change',
  promotionCode: 'Promotion code',
  selectCode: 'Select a code',
  pay: 'Order',
  upComing: 'Up coming',
  playback: 'Playback',
  live: 'Live',
  remindMe: 'Remind me',
  cancelRemind: 'Cancel remind',
  viewDetail: 'View detail',
  thereAre: 'There are',
  expireDate: 'Expire date',
  follower: 'Follower',
  changePassword: 'Change password',
  guideLine: 'Guide line',
  newsDetail: 'News detail',
  youHave: 'You have',
  pointPurchase: 'Point of purchase',
  pointUsage: 'Point usage',
  pointRemaining: 'point Remaining',
  howToGetPoint: 'Hot to get point?',
  voucher: 'vouchers',
  name: 'Tên',
  dob: 'Birthday',
  city: 'City',
  district: 'District',
  ward: 'Ward',
  address: 'Address',
  goBack: 'Go back',
  save: 'Save',
  oldPassword: 'Old password',
  newPassword: 'New password',
  reNewPassword: 'Re-new password',
  fieldRequired: 'Field required',
  version: 'Version',
  checkVersion: 'Check version',
  language: 'Language',
  pleaseChooseLanguage: 'Please choose a language below',
  warning: 'Warning',
  confirmLogout: 'Confirm logout',
  yes: 'Yes',
  no: 'No',
  confirmDelete: 'Confirm delete?',
  addToCartSuccess: 'Add to cart successfully',
  pleaseChooseInfoBelow: 'Please choose information below',
  quantity: 'Quantity',
  apply: 'Apply',
  cart: 'Cart',
  promotionList: 'Promotion list',
  COD: 'Cash on delivery',
  Point: 'Point',
  orderSuccess: 'Order successfully',
  orderWillSend: 'The system has saved the invoice you just placed. Delivery will be available to you in the next 2-3 days.',
  continueShopping: 'Continue shopping',
  noLiveStream: 'No any livestream',
  noUpComing: 'No any up coming',
  noPlayback: 'No any playback',
  LIVE: 'Live',
  PLAYBACK: 'Playback',
  phoneContinue: 'Continue with phone',
  willReceiveOtp: 'You’ll recevice a OTP code to verify your account.',
  enterPhone: 'Enter your phone number',
  next: 'Next',
  pleaseTypeOtp: 'Please type the verification code sent to',
  resendOtp: 'Resend OTP after',
  notReceiveOtp: 'Didn’t receive our OTP?',
  pleaseAddYourInformation: 'Please add your information below. You also can update it later in profile page.',
  additionalInformation: 'Additional information',
  enterPassword: 'Enter your password',
  myPage: 'My page',
  login: 'Login',
  forgotPassword: 'Forgot password',
  enterNewPassword: 'Enter your new password',
  forgotSuccess: 'Reset password successfully! Please login',
  reset: 'Reset',
  passwordNotEmpty: 'Password is not empty',
  passwordNotMatch: 'Two password are not match'
}