export const vi = {
  point: 'Điểm',
  myPurchase: 'Đơn hàng của tôi',
  news: 'Tin tức',
  notification: 'Thông báo',
  myPoint: 'Điểm của tôi',
  myPromotion: 'Khuyến mãi',
  myProfile: 'Trang cá nhân',
  changPassword: 'Đổi mật khẩu',
  setting: 'Cài đặt',
  logout: 'Đăng xuất',
  recent: 'Sản phẩm vừa xem',
  viewAll: 'Xem tất cả',
  system: 'Hệ thống',
  termAndPolicy: 'Chính sách và điều khoản',
  faq: 'Câu hỏi thường gặp',
  all: 'Tất cả',
  new: 'Mới',
  toShip: 'Đang giao',
  toReceive: 'Đã nhận',
  deliveryTo: 'Giao tới',
  productSelected: 'Sản phẩm đã chọn',
  paymentMethod: 'Phương thức thanh toán',
  summary: 'Tổng',
  subTotal: 'Tạm tính',
  promotionAmount: 'Giảm giá',
  shipFee: 'Phí vận chuyển',
  total: 'Tổng tiền',
  cancelInvoice: 'Hủy đơn',
  cartEmpty: 'Giỏ hàng trống',
  shoppingNow: 'Mua sắm ngay',
  myCart: 'Giỏ hàng',
  category: 'Danh mục',
  home: 'Trang chủ',
  following: 'Đang theo dõi',
  Fashion: 'Thời trang',
  Beauty: 'Làm đẹp',
  Food: 'Thức ăn',
  ['Healthy Foods']: 'Thực phẩm sạch',
  myFollow: 'Theo dõi',
  follow: 'Theo dõi',
  products: 'Sản phẩm',
  addToCart: 'Thêm vào giỏ',
  productInfo: 'Thông tin',
  review: 'Đánh giá',
  introduce: 'Giới thiệu',
  madeIn: 'Sản xuất tại',
  goToCart: 'Xem giỏ hàng',
  confirmOrder: 'Xác nhận đơn hàng',
  payment: 'Thanh toán',
  change: 'Thay đổi',
  promotionCode: 'Mã khuyến mãi',
  selectCode: 'Chọn mã',
  pay: 'Đặt hàng',
  upComing: 'Sắp diễn ra',
  playback: 'Xem lại',
  live: 'Trực tiếp',
  remindMe: 'Nhắc tôi',
  cancelRemind: 'Hủy nhắc nhở',
  viewDetail: 'Xem chi tiết',
  thereAre: 'Bạn có',
  expireDate: 'Ngày hết hạn',
  follower: 'Người theo dõi',
  changePassword: 'Đổi mật khẩu',
  guideLine: 'Hướng dẫn sử dụng',
  newsDetail: 'Chi tiết tin',
  youHave: 'Bạn có',
  pointPurchase: 'Điểm mua hàng',
  pointUsage: 'Điểm đã sử dụng',
  pointRemaining: 'Điểm còn lại',
  howToGetPoint: 'Làm thể nào để có điểm?',
  voucher: 'phiếu',
  name: 'Tên',
  dob: 'Ngày sinh nhật',
  city: 'Thành phố',
  district: 'Quận, huyện',
  ward: 'Phường, xã',
  address: 'Địa chỉ',
  goBack: 'Quay lại',
  save: 'Lưu',
  oldPassword: 'Mật khẩu cũ',
  newPassword: 'Mật khẩu mới',
  reNewPassword: 'Nhập lại mật khẩu mới',
  fieldRequired: 'Trường này bắt buộc',
  version: 'Phiên bản',
  checkVersion: 'Kiểm tra phiên bản',
  language: 'Ngôn ngữ',
  pleaseChooseLanguage: 'Vui lòng chọn ngôn ngữ ở dưới đây',
  warning: 'Cảnh báo',
  confirmLogout: 'Bạn chắc chắn đăng xuất',
  yes: 'Có',
  no: 'Không',
  confirmDelete: 'Bạn chắc chắn muốn xóa?',
  addToCartSuccess: 'Đã thêm vào giỏ hàng',
  pleaseChooseInfoBelow: 'Vui lòng chọn thông tin bên dưới',
  quantity: 'Số lượng',
  apply: 'Áp dụng',
  cart: 'Giỏ hàng',
  promotionList: 'Danh sách khuyến mãi',
  COD: 'Thanh toán khi nhận hàng',
  Point: 'Điểm',
  orderSuccess: 'Đặt hàng thành công',
  orderWillSend: 'Hệ thống đã nhận đơn hàng của bạn. Đơn hàng này sẽ được giao tới bạn trong 2 - 3 ngày sau.',
  continueShopping: 'Tiếp tục mua sắm',
  noLiveStream: 'Không có dữ liệu!',
  noUpComing: 'Không có dữ liệu',
  noPlayback: 'Không có dữ liệu',
  LIVE: 'Live',
  PLAYBACK: 'Xem lại',
  phoneContinue: 'Tiếp tục với số điện thoại',
  willReceiveOtp: 'Bạn sẽ nhận mã OTP để xác thực tài khoản',
  enterPhone: 'Nhập số điện thoại của bạn',
  next: 'Tiếp',
  pleaseTypeOtp: 'Vui lòng nhập mã OTP đã gửi đến',
  resendOtp: 'Gửi lại OTP sau',
  notReceiveOtp: 'Không nhận được mã?',
  pleaseAddYourInformation: 'Vui lòng điền thêm thông tin của bạn vào bên dưới. Bạn có thể cập nhật lại ở trang cá nhân của bạn',
  additionalInformation: 'Thông tin bổ sung',
  enterPassword: 'Nhập mật khẩu',
  myPage: 'Cá nhân',
  login: 'Đăng nhập',
  forgotPassword: 'Quên mật khẩu',
  enterNewPassword: 'Nhập mật khẩu mới để cập nhật mật khẩu cho tài khoản của bạn',
  forgotSuccess: 'Lấy lại mật khẩu thành công. Vui lòng đăng nhập để tiếp tục',
  reset: 'Đặt lại',
  passwordNotEmpty: 'Mật khẩu không để trống',
  passwordNotMatch: 'Mật khẩu mới không khớp'
}